//! WIT-generated bindings for `wit/plamenix.wit`.
//!
//! `wasmtime::component::bindgen!` expands at compile time into:
//!
//! * `PluginMinimal` — the world struct, with `instantiate_async` and
//!   typed accessors for the imported and exported interfaces.
//! * `plamenix::plugin::host::Host` — the trait the host implements
//!   to satisfy the plugin's imports.
//! * `plamenix::plugin::plugin::HostPluginInterface` — exported plugin
//!   accessor (`call_activate`).
//!
//! Higher-tier worlds (`plugin-db-reader`, `plugin-db-writer`,
//! `plugin-integrated`, `plugin-integrated-desktop`) live in the same
//! WIT package; their bindings get generated by parallel `bindgen!`
//! invocations as the consumers wiring them up land in Sections I1/I3
//! /I6/I7. Starting with `plugin-minimal` preserves the existing host
//! linker setup until those land.

#![allow(missing_docs, clippy::all)]

wasmtime::component::bindgen!({
    path: "wit",
    world: "plugin-minimal",
    async: true,
    trappable_imports: true,
});
