//! The metadata schema, and how it is created idempotently.
//!
//! Firebird has no `CREATE TABLE IF NOT EXISTS`. The portable way to
//! get the same effect is to ask `RDB$RELATIONS` first, which is what
//! [`SCHEMA_STATEMENTS`] does inside an `EXECUTE BLOCK` — one round
//! trip per object, and a second run is a no-op rather than an error
//! the caller has to recognise and swallow.
//!
//! Swallowing "object already exists" was the alternative and it is
//! worse: it also swallows the case where the object exists with the
//! wrong shape.

/// Statements that bring an empty database up to the current schema.
///
/// Each is independently idempotent, so the set can be re-run on every
/// open. Firebird's DDL is transactional, but mixing DDL and DML in one
/// transaction is a way to meet `object in use` errors, so the caller
/// runs these one at a time and commits between them.
pub const SCHEMA_STATEMENTS: &[&str] = &[
    // ---- query history ------------------------------------------
    //
    // `GENERATED BY DEFAULT AS IDENTITY` rather than a generator and a
    // trigger: Firebird 3 added it, the app requires 3.0+ anyway, and
    // it keeps the table readable by anyone who opens this database in
    // Plamenix itself — which they will, because it is a Firebird file
    // and this is a Firebird IDE.
    r#"EXECUTE BLOCK AS BEGIN
        IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'QUERY_HISTORY')) THEN
            EXECUTE STATEMENT '
                CREATE TABLE QUERY_HISTORY (
                    ID           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    PROFILE_ID   VARCHAR(64)   NOT NULL,
                    SQL_TEXT     BLOB SUB_TYPE TEXT NOT NULL,
                    EXECUTED_AT  BIGINT        NOT NULL,
                    DURATION_MS  BIGINT        NOT NULL,
                    STATUS       VARCHAR(16)   NOT NULL,
                    ERROR        BLOB SUB_TYPE TEXT,
                    -- `ROW_COUNT` is a Firebird context variable, so it
                    -- cannot be a column name. SQLite accepted it, which
                    -- is one small way the two engines differ that only
                    -- shows up when you actually run against the target.
                    ROWS_RETURNED BIGINT,
                    LABEL        VARCHAR(255)
                )';
    END"#,
    r#"EXECUTE BLOCK AS BEGIN
        IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_HISTORY_PROFILE')) THEN
            EXECUTE STATEMENT '
                CREATE DESCENDING INDEX IDX_HISTORY_PROFILE
                    ON QUERY_HISTORY (PROFILE_ID, EXECUTED_AT)';
    END"#,
    // ---- plugin grants ------------------------------------------
    //
    // The pair is the key. A grant is a fact about (plugin,
    // capability); recording it twice would make revocation ambiguous.
    r#"EXECUTE BLOCK AS BEGIN
        IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'PLUGIN_GRANTS')) THEN
            EXECUTE STATEMENT '
                CREATE TABLE PLUGIN_GRANTS (
                    PLUGIN_ID   VARCHAR(128) NOT NULL,
                    PERMISSION  VARCHAR(255) NOT NULL,
                    GRANTED_AT  BIGINT       NOT NULL,
                    PRIMARY KEY (PLUGIN_ID, PERMISSION)
                )';
    END"#,
    // ---- audit log ----------------------------------------------
    //
    // Append-only by discipline rather than by constraint: Firebird has
    // no way to forbid DELETE to the owner, and the owner is us. What
    // it does have is a separate table nothing else writes to, which is
    // enough for the log to survive a bug in the code it is auditing.
    //
    // `ACTOR` is the token name under the named-token scheme, so the
    // log can say which operator did something rather than only that
    // someone did. It is nullable because a request refused *before*
    // authentication — a bad Host, a missing token — is exactly the
    // kind of event worth recording and has no actor by definition.
    r#"EXECUTE BLOCK AS BEGIN
        IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'AUDIT_LOG')) THEN
            EXECUTE STATEMENT '
                CREATE TABLE AUDIT_LOG (
                    ID          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    OCCURRED_AT BIGINT       NOT NULL,
                    ACTOR       VARCHAR(64),
                    REMOTE_ADDR VARCHAR(64),
                    ACTION      VARCHAR(64)  NOT NULL,
                    TARGET      VARCHAR(255),
                    OUTCOME     VARCHAR(16)  NOT NULL,
                    DETAIL      BLOB SUB_TYPE TEXT
                )';
    END"#,
    r#"EXECUTE BLOCK AS BEGIN
        IF (NOT EXISTS (SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_AUDIT_TIME')) THEN
            EXECUTE STATEMENT '
                CREATE DESCENDING INDEX IDX_AUDIT_TIME ON AUDIT_LOG (OCCURRED_AT)';
    END"#,
];
