//! Emits a single TypeScript file containing every Plamenix wire type.
//!
//! The output is written to
//! `../plamenix-ui/src/db/generated.ts` relative to the workspace root
//! (i.e. one level up from this crate's workspace). The path can be
//! overridden by passing it as the first CLI argument.
//!
//! Run with `just ts-gen` (defined in `plamenix-core/justfile`) or
//! directly: `cargo run -p plamenix-ts-gen`.

use std::path::PathBuf;
use std::process::ExitCode;

use plamenix_db::{Column, ColumnValue, CryptState, QueryResult, Row, StatementOutcome};
use plamenix_profiles::{Profile, ProfileId};
use plamenix_types::{
    AttachmentInfo, ColumnInfo, ConnectionConfig, DatabaseAlias, DatabaseStats, DomainInfo,
    GeneratorInfo, HistoryEntry, ListAliasesResult, MonDatabase, ProcedureInfo, Schema, SessionId,
    StatementInfo, TabId, TableInfo, TableKind, TestConnectionResult, TriggerInfo,
};
use specta::Types;
use specta::datatype::Primitive;
use specta_typescript::Typescript;
use specta_util::Remapper;

const DEFAULT_OUTPUT: &str = "../plamenix-ui/src/db/generated.ts";

const HEADER: &str = "// AUTO-GENERATED by `plamenix-ts-gen` (see crates/plamenix-ts-gen).\n\
                      // DO NOT EDIT BY HAND. Run `just ts-gen` from plamenix-core to refresh.\n\
                      /* eslint-disable */\n";

fn main() -> ExitCode {
    let out = std::env::args()
        .nth(1)
        .map_or_else(|| PathBuf::from(DEFAULT_OUTPUT), PathBuf::from);

    let types = Types::default()
        .register::<SessionId>()
        .register::<TabId>()
        .register::<ConnectionConfig>()
        .register::<Schema>()
        .register::<TableInfo>()
        .register::<TableKind>()
        .register::<ColumnInfo>()
        .register::<ProcedureInfo>()
        .register::<TriggerInfo>()
        .register::<GeneratorInfo>()
        .register::<DomainInfo>()
        .register::<TestConnectionResult>()
        .register::<HistoryEntry>()
        .register::<DatabaseAlias>()
        .register::<ListAliasesResult>()
        .register::<DatabaseStats>()
        .register::<MonDatabase>()
        .register::<AttachmentInfo>()
        .register::<StatementInfo>()
        .register::<CryptState>()
        .register::<ColumnValue>()
        .register::<Column>()
        .register::<Row>()
        .register::<QueryResult>()
        .register::<StatementOutcome>()
        .register::<Profile>()
        .register::<ProfileId>();

    // Specta forbids i64/u64 in TS output because JS numbers are exact
    // only to 2^53. The remaining i64s here are bounded by construction
    // — epoch milliseconds, page counts, durations, ODS versions — so
    // the loss cannot bite and we remap them to i32 to get a plain
    // `number` rather than a refusal.
    //
    // Integers whose magnitude the user controls are NOT covered by
    // this: `ColumnValue::Integer` and `GeneratorInfo.current_value`
    // carry full-range Firebird BIGINTs and are declared
    // `#[specta(type = String)]` at their definitions, so they reach TS
    // as exact decimal text. Anything new of that kind belongs there
    // too, not here.
    let remap = Remapper::new()
        .rule(Primitive::i64.into(), Primitive::i32.into())
        .rule(Primitive::u64.into(), Primitive::i32.into())
        .rule(Primitive::usize.into(), Primitive::i32.into())
        .rule(Primitive::isize.into(), Primitive::i32.into())
        .rule(Primitive::i128.into(), Primitive::i32.into())
        .rule(Primitive::u128.into(), Primitive::i32.into());
    let types = remap.remap_types(types);

    let exporter = Typescript::default().header(HEADER);
    if let Err(err) = exporter.export_to(&out, &types, specta_serde::Format) {
        eprintln!("ts-gen failed: {err}");
        return ExitCode::FAILURE;
    }

    println!("wrote {}", out.display());
    ExitCode::SUCCESS
}
