//! Emits a single TypeScript file containing every Plamenix wire type.
//!
//! The output is written to
//! `../plamenix-ui/src/db/generated.ts` relative to the workspace root
//! (i.e. one level up from this crate's workspace). The path can be
//! overridden by passing it as the first CLI argument.
//!
//! Run with `just ts-gen` (defined in `plamenix-core/justfile`) or
//! directly: `cargo run -p plamenix-ts-gen`.

use std::path::PathBuf;
use std::process::ExitCode;

use plamenix_db::{Column, ColumnValue, CryptState, QueryResult, Row, StatementOutcome};
use plamenix_profiles::{Profile, ProfileId};
use plamenix_types::{
    AttachmentInfo, ColumnInfo, ConnectionConfig, DatabaseAlias, DatabaseStats, DomainInfo,
    GeneratorInfo, HistoryEntry, ListAliasesResult, MonDatabase, ProcedureInfo, Schema, SessionId,
    StatementInfo, TabId, TableInfo, TableKind, TestConnectionResult, TriggerInfo,
};
use specta::Types;
use specta::datatype::Primitive;
use specta_typescript::Typescript;
use specta_util::Remapper;

const DEFAULT_OUTPUT: &str = "../plamenix-ui/src/db/generated.ts";

const HEADER: &str = "// AUTO-GENERATED by `plamenix-ts-gen` (see crates/plamenix-ts-gen).\n\
                      // DO NOT EDIT BY HAND. Run `just ts-gen` from plamenix-core to refresh.\n\
                      /* eslint-disable */\n";

fn main() -> ExitCode {
    let out = std::env::args()
        .nth(1)
        .map_or_else(|| PathBuf::from(DEFAULT_OUTPUT), PathBuf::from);

    let types = Types::default()
        .register::<SessionId>()
        .register::<TabId>()
        .register::<ConnectionConfig>()
        .register::<Schema>()
        .register::<TableInfo>()
        .register::<TableKind>()
        .register::<ColumnInfo>()
        .register::<ProcedureInfo>()
        .register::<TriggerInfo>()
        .register::<GeneratorInfo>()
        .register::<DomainInfo>()
        .register::<TestConnectionResult>()
        .register::<HistoryEntry>()
        .register::<DatabaseAlias>()
        .register::<ListAliasesResult>()
        .register::<DatabaseStats>()
        .register::<MonDatabase>()
        .register::<AttachmentInfo>()
        .register::<StatementInfo>()
        .register::<CryptState>()
        .register::<ColumnValue>()
        .register::<Column>()
        .register::<Row>()
        .register::<QueryResult>()
        .register::<StatementOutcome>()
        .register::<Profile>()
        .register::<ProfileId>();

    // The JS runtime can hold every Plamenix integer in its native
    // `number` type (epoch milliseconds, row counts, durations in ms all
    // sit well within 2^53). Specta is strict by default and forbids
    // i64/u64 in TS output to avoid silent precision loss; we accept
    // that loss explicitly and remap to i32 so the printer emits plain
    // `number` rather than refusing.
    let remap = Remapper::new()
        .rule(Primitive::i64.into(), Primitive::i32.into())
        .rule(Primitive::u64.into(), Primitive::i32.into())
        .rule(Primitive::usize.into(), Primitive::i32.into())
        .rule(Primitive::isize.into(), Primitive::i32.into())
        .rule(Primitive::i128.into(), Primitive::i32.into())
        .rule(Primitive::u128.into(), Primitive::i32.into());
    let types = remap.remap_types(types);

    let exporter = Typescript::default().header(HEADER);
    if let Err(err) = exporter.export_to(&out, &types, specta_serde::Format) {
        eprintln!("ts-gen failed: {err}");
        return ExitCode::FAILURE;
    }

    println!("wrote {}", out.display());
    ExitCode::SUCCESS
}
